services:
  web:
    build:
      context: .
      target: runner
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      - worker
    networks:
      - dokploy-network
    env_file:
      - .env

  worker:
    build:
      context: .
      target: cron
    restart: unless-stopped
    networks:
      - dokploy-network
    env_file:
      - .env

networks:
  dokploy-network:
    external: true
