services:
  web:
    build:
      context: .
      target: runner
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      - worker

  worker:
    build:
      context: .
      target: cron
    restart: unless-stopped
