# docker-compose.yaml
version: '3.8'
services:
  jenkins:
      container_name: jenkins
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
      - 8080:8080
      - 50000:50000
      volumes:
        - /home/opc/jenkins/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - "./traefik.yml:/etc/traefik/traefik.yml"
        - "./letsencrypt:/letsencrypt"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$2y$05$9kG4DbiUWBkVl2fz7nSnsOYS4jZzgGa0j1CrZAExoeEgPcYl1iCzu"
        - "traefik.http.routers.traefik.rule=Host(`jenkins.ahmedlotfy.me`)"
        - "traefik.http.routers.traefik.middlewares=traefik-auth"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      networks:
        - proxy