export const booksAppProjectData = [{
    "title_en": "Virtual Book App",
    "title_ar": "تطبيق المكتبة الافتراضية",
    "slug": "book-app",
    "desc_en": "A modern, full-stack bookstore featuring real-time data from Google Books & NYT APIs, powered by a high-performance Redis caching layer and a type-safe Drizzle/PostgreSQL backend.",
    "desc_ar": "متجر كتب حديث ومتكامل يعرض بيانات حقيقية من واجهات برمجة تطبيقات Google Books و NYT، مدعوم بطبقة تخزين مؤقت عالية الأداء باستخدام Redis وخلفية آمنة (Type-safe) باستخدام Drizzle و PostgreSQL.",
    "content_en": "# The Vision\nThe Virtual Book App was conceived as a modern, feature-rich platform to bridge the gap between book discovery and personal library management. My goal was to create a seamless experience where users can not only find bestsellers and search specifically for their interests but also curate their own reading wishlists. I wanted to move beyond a simple CRUD application and build a system that aggregates real-world data from robust APIs (Google Books and NY Times) while maintaining high performance and a polished UI.\n\n# The Challenge\nBuilding a \"books\" application might sound simple, but doing it right presented several complex challenges:\n- **Data Aggregation & Performance**: Relying on external APIs like Google Books and NY Times means potential latency and rate limits. Presenting this data instantly to the user required a strategy beyond simple fetch calls.\n- **Modern Backend Architecture**: Instead of opting for the familiar Mongoose/MongoDB stack, I chose to embrace modern SQL practices using **PostgreSQL** and **Drizzle ORM**. This required rethinking data modeling to ensure strict type safety and efficient relational queries.\n- **State Management**: with a multi-page app (Search, Details, Wishlist), managing the global state of the user's session and book collections without prop-drilling was critical.\n- **Authentication & Security**: Implementing secure session-based authentication enabling users to persist their private collections across devices.\n\n# The Solution\nI engineered a full-stack solution that balances a responsive frontend with a robust, type-safe backend:\n\n- **Intelligent Caching with Redis**: To solve the API latency issue, I implemented a Redis caching layer. Popular searches and bestseller lists are cached, ensuring near-instant load times for subsequent requests and significantly reducing API usage.\n- **Type-Safe Database Layer**: By using **Drizzle ORM** with **PostgreSQL**, I ensured that the database interactions are completely type-safe from the entry point to the query execution. This drastically reduced runtime errors and improved developer velocity.\n- **Responsive & Polished UI**: Built with **React** and **TailwindCSS**, the interface is fully responsive. I used **Zustand** for lightweight, effective global state management to handle user sessions and wishlist updates seamlessly.\n- **Comprehensive Features**: \n    - **Advanced Search & Filter**: Users can filter by category, language, and sorting preferences.\n    - **OAuth Integration**: Frictionless sign-in with Google.\n    - **Dynamic Routing**: Detailed views for every book with deep linking support.",
    "content_ar": "# الرؤية\nتم انشاء تطبيق المكتبة الافتراضية كمنصة حديثة وغنية بالميزات لسد الفجوة بين استكشاف الكتب وإدارة المكتبات الشخصية. كان هدفي هو خلق تجربة سلسة حيث لا يكتفي المستخدمون بالعثور على الكتب الأكثر مبيعًا والبحث عن اهتماماتهم فحسب، بل يمكنهم أيضًا تنظيم قوائم القراءة الخاصة بهم. أردت تجاوز تطبيقات CRUD البسيطة وبناء نظام يجمع بيانات حقيقية من واجهات برمجة تطبيقات قوية (Google Books و NY Times) مع الحفاظ على الأداء العالي وواجهة مستخدم مصقولة.\n\n# التحدي\nقد يبدو بناء تطبيق \"كتب\" أمرًا بسيطًا، لكن القيام بذلك بشكل صحيح واجه عدة تحديات معقدة:\n- **تجميع البيانات والأداء**: الاعتماد على واجهات خارجية مثل Google Books و NY Times يعني احتمال وجود تأخير وقيود على معدل الطلبات. تقديم هذه البيانات فورًا للمستخدم تطلب استراتيجية تتجاوز مجرد طلبات الجلب العادية.\n- **هندسة الخلفية الحديثة**: بدلاً من اختيار حزمة Mongoose/MongoDB المألوفة، اخترت تبني ممارسات SQL الحديثة باستخدام **PostgreSQL** و **Drizzle ORM**. تطلب ذلك إعادة التفكير في نمذجة البيانات لضمان أمان الأنواع (Type Safety) واستعلامات علائقية فعالة.\n- **إدارة الحالة**: مع تطبيق متعدد الصفحات (بحث، تفاصيل، قائمة أمنيات)، كانت إدارة الحالة العامة لجلسة المستخدم ومجموعات الكتب دون تعقيد الكود أمرًا بالغ الأهمية.\n- **المصادقة والأمان**: تنفيذ مصادقة آمنة تعتمد على الججلسات لتمكين المستخدمين من الاحتفاظ بمجموعاتهم الخاصة عبر الأجهزة.\n\n# الحل\nقمت بهندسة حل متكامل يوازن بين واجهة أمامية سريعة الاستجابة وخلفية قوية وآمنة:\n\n- **التخزين المؤقت الذكي باستخدام Redis**: لحل مشكلة تأخير الواجهات البرمجية، قمت بتنفيذ طبقة تخزين مؤقت باستخدام Redis. يتم تخزين عمليات البحث الشائعة وقوائم الأكثر مبيعًا مؤقتًا، مما يضمن أوقات تحميل شبه فورية للطلبات اللاحقة ويقلل بشكل كبير من استخدام الواجهة البرمجية.\n- **طبقة قاعدة بيانات آمنة النوع**: باستخدام **Drizzle ORM** مع **PostgreSQL**، ضمنت أن تكون تفاعلات قاعدة البيانات آمنة تمامًا من حيث الأنواع (Type-safe) من نقطة الدخول وحتى تنفيذ الاستعلام. أدى هذا إلى تقليل أخطاء وقت التشغيل بشكل كبير وتحسين سرعة التطوير.\n- **واجهة مستخدم متجاوبة ومصقولة**: تم بناؤها باستخدام **React** و **TailwindCSS**، والواجهة متجاوبة بالكامل. استخدمت **Zustand** لإدارة الحالة العامة بشكل خفيف وفعال للتعامل مع جلسات المستخدم وتحديثات قائمة الأمنيات بسلاسة.\n- **ميزات شاملة**:\n    - **بحث وتصفية متقدمة**: يمكن للمستخدمين التصفية حسب الفئة، واللغة، وتفضيلات الفرز.\n    - **تكامل OAuth**: تسجيل دخول سلس باستخدام Google.\n    - **توجيه ديناميكي**: عروض تفصيلية لكل كتاب مع دعم الروابط العميقة.",
    "categories": [
      "Fullstack",
      "React",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "Drizzle ORM",
      "Redis"
    ],
    "published": true,
    "repoLink": "https://github.com/chingu-voyages/v43-tier2-team-14",
    "liveLink": "https://books-app.ahmedlotfy.site/",
    "imageLink": "https://images.ahmedlotfy.site/projects/Books-Project.png",
    "displayOrder": 1
  }];
