export const hiXProjectData = [{
    "title_en": "hi-x.net - LinkTree",
    "title_ar": "hi-x.net - LinkTree",
    "slug": "hi-x",
    "desc_en": "A professional bilingual portfolio and educational hub for Mohamed Ali (Captain X), a financial markets trader and trainer expert in Golden Ratio analysis.",
    "desc_ar": "معرض أعمال ومركز تعليمي احترافي ثنائي اللغة لمحمد علي (كابتن إكس)، متداول ومدرب في الأسواق المالية وخبير في تحليل النسبة الذهبية.",
    "content_en": "# The Vision\nMy goal with the \"Captain X\" project was to elevate the personal brand of Mohamed Ali, a professional trader, by creating a premium, bilingual (English & Arabic) web presence. The vision was to move away from a generic look to a custom, high-performance interface that instills trust and professionalism, reflecting his expertise in financial markets and the \"Golden Ratio\" trading method.\n\n# The Challenge\nThe previous version of the site (`hi-x-old-code`) was functional but lacked the polish and performance required for a high-profile personal brand.\nKey challenges included:\n- **Performance**: The old site suffered from unoptimized assets and heavy libraries (like Font Awesome) that slowed down load times.\n- **Mobile Experience**: The mobile view was not fully optimized, with background images and layout spacing that didn't adapt well to smaller screens.\n- **Project Structure**: The codebase was disorganized, making it difficult to maintain or scale.\n- **Bilingual Support**: While present, the implementation needed refinement to ensure a smooth experience across both RTL (Arabic) and LTR (English) layouts.\n\n# The Solution\nI undertook a complete overhaul of the codebase (`hi-x-new-code`), focusing on performance, structure, and user experience.\n\n- **Architecture & Structure**: I reorganized the project into a standard, maintainable structure with dedicated `css/`, `js/`, and `images/` directories. I implemented a build process that outputs a clean `html/` distribution bundle.\n- **Performance Optimization**:\n    - Replaced heavy libraries with a custom selection of optimized SVG icons (`images/icons/`).\n    - Implemented responsive image serving using the `<picture>` tag and WebP formats to ensure fast loading on all devices.\n    - Minified CSS and JavaScript assets (`styles-min.css`, `main-min.js`).\n- **Responsive Design**: Redesigned the mobile experience, specifically the top section and background handling, to ensure pixel-perfect rendering on phones without compromising the desktop visual.\n- **Enhanced Content**: Added a new `about-us.html` page and expanded the home pages with richer content and better SEO meta tags for both English and Arabic.\n- **Professional Polish**: Introduced a sleek, modern design language with consistent typography (Inter, Poppins, Cairo) and a refined color palette, matching the \"Captain X\" brand identity.",
    "content_ar": "# الرؤية\nكان هدفي من مشروع \"Captain X\" هو الارتقاء بالعلامة التجارية الشخصية لمحمد علي، المتداول المحترف، من خلال إنشاء حضور وب مميز وثنائي اللغة (الإنجليزية والعربية). كانت الرؤية تتمثل في الانتقال من المظهر التقليدي إلى واجهة مخصصة عالية الأداء تبعث على الثقة والاحترافية، وتعكس خبرته في الأسواق المالية وطريقة تداول \"النسبة الذهبية\".\n\n# التحدي\nكانت النسخة السابقة من الموقع (`hi-x-old-code`) تعمل، لكنها كانت تفتقر إلى اللمسات الجمالية والأداء المطلوب لعلامة تجارية شخصية بارزة.\nتضمنت التحديات الرئيسية ما يلي:\n- **الأداء**: كان الموقع القديم يعاني من أصول غير محسّنة ومكتبات ثقيلة (مثل Font Awesome) مما أبطأ أوقات التحميل.\n- **تجربة الجوال**: لم تكن نسخة الجوال محسّنة بالكامل، مع مشاكل في صور الخلفية ومسافات التخطيط التي لم تتناسب جيدًا مع الشاشات الصغيرة.\n- **هيكلية المشروع**: كان الكود غير منظم، مما جعل من الصعب صيانته أو تطويره.\n- **الدعم ثنائي اللغة**: على الرغم من وجوده، كان التنفيذ بحاجة إلى تحسين لضمان تجربة سلسة عبر كل من التخطيطات من اليمين لليسار (Arabic) ومن اليسار لليمين (English).\n\n# الحل\nقمت بإجراء إصلاح شامل للكود (`hi-x-new-code`)، مع التركيز على الأداء، والهيكلية، وتجربة المستخدم.\n\n- **الهيكلية والتنظيم**: أعدت تنظيم المشروع في هيكل قياسي قابل للصيانة مع مجلدات مخصصة لـ `css/` و `js/` و `images/`. قمت بتنفيذ عملية بناء تخرج حزمة `html/` نظيفة وجاهزة للنشر.\n- **تحسين الأداء**:\n    - استبدلت المكتبات الثقيلة بمجموعة مخصصة من أيقونات SVG المحسّنة (`images/icons/`).\n    - قمت بتنفيذ عرض الصور المتجاوب باستخدام وسم `<picture>` وتنسيقات WebP لضمان التحميل السريع على جميع الأجهزة.\n    - قمت بضغط ملفات CSS و JavaScript (`styles-min.css`, `main-min.js`).\n- **التصميم المتجاوب**: أعدت تصميم تجربة الجوال، وتحديداً القسم العلوي ومعالجة الخلفية، لضمان عرض دقيق (pixel-perfect) على الهواتف دون التأثير على جودة العرض على سطح المكتب.\n- **تحسين المحتوى**: أضفت صفحة `about-us.html` جديدة ووسعت الصفحات الرئيسية بمحتوى أكثر ثراءً وعلامات SEO وصفية أفضل لكل من الإنجليزية والعربية.\n- **لمسة احترافية**: قدمت لغة تصميم حديثة وأنيقة مع خطوط متناسقة (Inter, Poppins, Cairo) ولوحة ألوان راقية تتناسب مع هوية العلامة التجارية \"Captain X\".",
    "categories": [
      "Frontend",
      "HTML/CSS",
      "JavaScript",
      "Optimization",
      "Bilingual",
      "Financial"
    ],
    "published": true,
    "repoLink": "https://github.com/ahmed-lotfy-dev/hi-x",
    "liveLink": "https://hi-x.com",
    "imageLink": "https://images.ahmedlotfy.site/projects/hi-x-net-2025-10-07-18_23_54.png",
    "displayOrder": 3
  }];
