export const experiencesSeedData = [
  {
    company: "The Drive Center",
    role_en: "Senior Software Architect & Full-Stack Engineer",
    role_ar: "كبير معماري البرمجيات ومطور Full-Stack",
    date_en: "May 2024 — Present",
    date_ar: "مايو ٢٠٢٤ — دلوقتي",
    description_en: "Architected a high-performance automotive SaaS platform with automated booking, vehicle tracking, and WhatsApp API integration. Optimized for Local SEO and performance using Next.js 16 and Drizzle ORM. Resulted in a 40% reduction in administrative overhead.",
    description_ar: "صممت ونفذت نظام فني متكامل لمركز صيانة سيارات. شملت المنصة نظام حجز ذكي، تتبع لحالة المركبات، وربط مع WhatsApp API. تم تحسين الموقع لمحركات البحث المحلية والأداء العالي باستخدام Next.js 16 و Drizzle ORM. النتيجة: تقليل الأعباء الإدارية بنسبة ٤٠٪.",
    tech_stack: ["Next.js 16", "TypeScript", "PostgreSQL", "Drizzle ORM", "Better Auth", "Cloudflare R2", "WhatsApp API"],
    displayOrder: 1,
    published: true,
  },
  {
    company: "Zamalek Store",
    role_en: "Lead Full-Stack Engineer",
    role_ar: "Lead Full-Stack Engineer",
    date_en: "Oct — Dec 2024",
    date_ar: "أكتوبر — ديسمبر ٢٠٢٤",
    description_en: "Digital transformation for a major clothing brand. Built a high-performance e-commerce engine (Next.js 16) handling high traffic. Integrated Paymob payments and localized workflows. Result: 40% reduction in cart abandonment and significant increase in online sales volume through 24/7 availability.",
    description_ar: "تحول رقمي لعلامة تجارية كبرى للملابس. قمت ببناء محرك تجارة إلكترونية عالي الأداء (Next.js 16) يتعامل مع حركة مرور عالية. دمجت مدفوعات Paymob وسير عمل محلي. النتيجة: انخفاض بنسبة 40% في ترك سلة التسوق وزيادة كبيرة في حجم المبيعات عبر الإنترنت من خلال التوفر على مدار الساعة طوال أيام الأسبوع.",
    tech_stack: ["Next.js 16", "PostgreSQL", "BullMQ", "Redis", "Docker", "Paymob"],
    displayOrder: 2,
    published: true,
  },
  {
    company: "Toota Art Gallery",
    role_en: "Full-Stack Developer (Contract)",
    role_ar: "Full-Stack Developer (Contract)",
    date_en: "May — June 2024",
    date_ar: "مايو — يونيو ٢٠٢٤",
    description_en: "Engineered a digital asset management system for a visual arts gallery. Implemented Cloudflare R2 object storage to serve high-resolution art assets globally with low latency. Optimized hosting architecture to reduce monthly infrastructure costs while maintaining 99.9% uptime.",
    description_ar: "هندسة نظام إدارة أصول رقمية لمعرض فنون بصرية. نفذت تخزين Cloudflare R2 لتقديم أصول فنية عالية الدقة عالميًا بزمن انتقال منخفض. تحسين بنية الاستضافة لتقليل تكاليف البنية التحتية الشهرية مع الحفاظ على وقت تشغيل بنسبة 99.9%.",
    tech_stack: ["Laravel", "Livewire", "Alpine.js", "Cloudflare R2"],
    displayOrder: 3,
    published: true,
  },
  {
    company: "Mohammed Ali (Captain X)",
    role_en: "Frontend Perf. Specialist",
    role_ar: "Frontend Perf. Specialist",
    date_en: "Feb — Mar 2024",
    date_ar: "فبراير — مارس ٢٠٢٤",
    description_en: "Consulted on modernizing a legacy web platform. Executed a mobile-first performance overhaul, implementing advanced image optimization and code-splitting strategies. Achieved perfect 95+ Core Web Vitals scores, directly improving SEO rankings and mobile user retention.",
    description_ar: "استشاري لتحديث منصة ويب قديمة. نفذت إصلاحًا شاملًا للأداء يعتمد على الموبايل أولاً، وتطبيق استراتيجيات متقدمة لتحسين الصور وتقسيم الكود. حققت درجات مثالية 95+ في مؤشرات أداء الويب الأساسية، مما أدى إلى تحسين مباشر في تصنيفات تحسين محركات البحث والاحتفاظ بمستخدمي الموبايل.",
    tech_stack: ["React", "Performance Optimization", "Responsive Design", "SEO"],
    displayOrder: 4,
    published: true,
  },
  {
    company: "Chingu",
    role_en: "Full-Stack Developer (Remote Team)",
    role_ar: "Full-Stack Developer (Remote Team)",
    date_en: "Jan — Mar 2024",
    date_ar: "يناير — مارس ٢٠٢٤",
    description_en: "Collaborated in an agile remote team environment to deploy a production-ready application. Focused on backend scalability and authentication security (Auth0). Established CI/CD workflows that reduced deployment time for the team.",
    description_ar: "تعاونت في بيئة فريق سريع عن بعد لنشر تطبيق جاهز للإنتاج. ركزت على قابلية التوسع في الواجهة الخلفية وأمان المصادقة (Auth0). أنشأت سير عمل CI/CD قلل وقت النشر للفريق.",
    tech_stack: ["React", "Node.js", "Express", "MongoDB", "Auth0"],
    displayOrder: 5,
    published: true,
  },
];
