export const experiencesSeedData = [
  {
    company: "Self-Directed Professional Development",
    role_en: "Full-Stack Developer",
    role_ar: "مطور واجهة كاملة",
    date_en: "May 2022 — Jan 2023",
    date_ar: "مايو ٢٠٢٢ — يناير ٢٠٢٣",
    description_en: "Undertook a rigorous 1,000+ hour self-directed engineering curriculum. Mastered frontend fundamentals via Jonas Schmedtmann’s 'Zero to Expert' JS series. Specialized in the React ecosystem through Udacity’s NanoDegree and ZTM mastery (Redux, Hooks, GraphQL). Pivoted to Full-Stack development by engineering robust Node.js architectures (REST/GraphQL/MVC) under Maximilian Schwarzmüller. Successfully delivered complex personal projects like a POS system and a Bookstore to validate architectural patterns.",
    description_ar: "أكملت منهجًا هندسيًا مكثفًا يزيد عن 1000 ساعة من التعلم الذاتي. أتقنت أساسيات الواجهة الأمامية عبر دورات Jonas Schmedtmann (JS Zero to Expert). تخصصت في نظام React من خلال Udacity NanoDegree و ZTM (Redux, Hooks, GraphQL). انتقلت إلى تطوير الواجهات الكاملة عبر هندسة برمجيات Node.js (REST/GraphQL/MVC) مع Maximilian Schwarzmüller. قمت بتسليم مشاريع شخصية بجودة احترافية مثل نظام POS ومتجر كتب للتحقق من الأنماط المعمارية.",
    tech_stack: ["React", "Node.js", "TypeScript", "GraphQL", "Redux", "PostgreSQL", "Docker"],
    displayOrder: 0,
    published: true,
  },
  {
    company: "Chingu",
    role_en: "Full-Stack Developer (Internship)",
    role_ar: "مطور واجهة كاملة (تدريب عملي)",
    date_en: "Mar — May 2024",
    date_ar: "مارس — مايو ٢٠٢٤",
    description_en: "Participated in an intensive 2-month collaborative internship, working in a remote agile team to architect and build a production-ready Books Application. Implemented full-stack features including user authentication, real-time book searching, and a personal library management system, adhering to professional software development workflows.",
    description_ar: "شاركت في تدريب عملي مكثف لمدة شهرين، حيث عملت ضمن فريق برمجيات عن بُعد لبناء تطبيق كتب متكامل (Books App). قمت بتنفيذ ميزات الواجهة الكاملة بما في ذلك مصادقة المستخدمين، والبحث الفوري عن الكتب، ونظام إدارة المكتبة الشخصية، مع الالتزام ببيئة عمل احترافية تعتمد على منهجية Agile.",
    tech_stack: ["React", "Node.js", "Express", "MongoDB", "Auth0"],
    displayOrder: 1,
    published: true,
  },
  {
    company: "Mohammed Ali (Captain X)",
    role_en: "Frontend Architect (Freelance)",
    role_ar: "مهندس واجهات أمامية (عمل حر)",
    date_en: "Feb — Mar 2025",
    date_ar: "فبراير — مارس ٢٠٢٥",
    description_en: "Re-engineered a legacy single-file HTML application into a professional, mobile-first web platform. Successfully optimized performance by implementing lazy loading, mobile-responsive image assets, and thorough code refactoring, achieving 95+ Core Web Vitals scores.",
    description_ar: "إعادة هندسة تطبيق قديم يعتمد على ملف HTML واحد وتحويله إلى منصة ويب احترافية تدعم الموبايل بشكل أساسي. نجحت في تحسين الأداء عبر تنفيذ التحميل الكسول (Lazy Loading)، وتوفير صور محسنة للتجاوب مع الموبايل، وإعادة هيكلة شاملة للكود، محققاً 95+ في مؤشرات أداء الويب.",
    tech_stack: ["React", "Performance Optimization", "Responsive Design", "SEO"],
    displayOrder: 2,
    published: true,
  },
  {
    company: "Toota Art Gallery",
    role_en: "Full-Stack Developer (Project)",
    role_ar: "مطور واجهة كاملة (مشروع عملي)",
    date_en: "May — June 2025",
    date_ar: "مايو — يونيو ٢٠٢٥",
    description_en: "A 1.5-month intensive practice project undertaken to master the Laravel ecosystem. Built a professional-grade digital asset management system for a visual arts gallery, implementing Cloudflare R2 object storage to optimize high-resolution image delivery and hosting costs.",
    description_ar: "مشروع تدريبي مكثف لمدة شهر ونصف لتمكين مهارات نظام Laravel. تم بناء نظام احترافي لإدارة الأصول الرقمية لمعرض فنون بصرية، مع تنفيذ تخزين Cloudflare R2 لتحسين تكلفة استضافة وتسليم الصور عالية الدقة.",
    tech_stack: ["Laravel", "Livewire", "Alpine.js", "Cloudflare R2"],
    displayOrder: 3,
    published: true,
  },
  {
    company: "Zamalek Store",
    role_en: "Lead Full-Stack Engineer (Contract)",
    role_ar: "مطور واجهة كاملة",
    date_en: "Oct — Dec 2025",
    date_ar: "أكتوبر — ديسمبر ٢٠٢٥",
    description_en: "Spearheaded the digital transformation of a prominent local clothing brand, transitioning their operations to a robust online presence. Architected a custom e-commerce engine with a hybrid cart system and integrated Paymob for seamless payments. Successfully increased sales volume by enabling 24/7 online shopping availability and optimized the checkout flow to reduce drop-offs by 40%.",
    description_ar: "قدت عملية التحول الرقمي لعلامة تجارية محلية بارزة للملابس، محولاً عملياتهم إلى تواجد قوي عبر الإنترنت. صممت محرك تجارة إلكترونية مخصصًا بنظام سلة هجين ودمجت بوابة Paymob للمدفوعات السلسة. نجحت في زيادة حجم المبيعات من خلال تفعيل التسوق عبر الإنترنت على مدار الساعة طوال أيام الأسبوع، وحسنت تدفق الدفع لتقليل التخلي عن السلة بنسبة 40%.",
    tech_stack: ["Next.js 16", "PostgreSQL", "BullMQ", "Redis", "Docker", "Paymob"],
    displayOrder: 4,
    published: true,
  },
];
