export const projectsSeedData = [
  {
    "title_en": "Task Hub — MCP-Driven Project Management",
    "title_ar": "Task Hub — إدارة المشاريع عبر طبقة MCP",
    "slug": "task-hub-mcp-driven-project-management",
    "desc_en": "A minimalist project manager I built for my own workflow, with an MCP server layer that turns PRDs and user stories into actionable tasks.",
    "desc_ar": "مدير مشاريع بسيط بنيته لعملي الشخصي، مع طبقة MCP تحول الـ PRD والقصص إلى مهام قابلة للتنفيذ.",
    "repoLink": "https://github.com/ahmed-lotfy-dev/task-hub",
    "liveLink": "https://task-hub.ahmedlotfy.site",
    "coverImage": "/images-downloaded/projects/task-hub-mcp-driven-project-management/task-hub-mcp-driven-project-management-1770684624710.webp",
    "categories": [],
    "displayOrder": 8,
    "published": true
  },
  {
    "title_en": "Virtual Book App",
    "title_ar": "تطبيق المكتبة الافتراضية",
    "slug": "book-app",
    "desc_en": "A modern, full-stack bookstore featuring real-time data from Google Books & NYT APIs, powered by a high-performance Redis caching layer and a type-safe Drizzle/PostgreSQL backend.",
    "desc_ar": "متجر كتب حديث ومتكامل يعرض بيانات حقيقية من واجهات برمجة تطبيقات Google Books و NYT، مدعوم بطبقة تخزين مؤقت عالية الأداء باستخدام Redis وخلفية آمنة (Type-safe) باستخدام Drizzle و PostgreSQL.",
    "repoLink": "https://github.com/chingu-voyages/v43-tier2-team-14",
    "liveLink": "https://books-app.ahmedlotfy.site/",
    "coverImage": "/images-downloaded/projects/Books-Project.png",
    "categories": ["Fullstack", "React", "TypeScript", "Node.js", "PostgreSQL", "Drizzle ORM", "Redis"],
    "displayOrder": 1,
    "published": true
  },
  {
    "title_en": "Zamalek Store",
    "title_ar": "متجر الزمالك",
    "slug": "zamalek-store",
    "desc_en": "A production-ready, bilingual e-commerce platform for Egyptian football fans. Built with Next.js 16, React 19, and Paymob/Kashier integration. Features a hybrid cart system, BullMQ background processing, and optimal mobile performance via Cloudflare R2.",
    "desc_ar": "منصة تجارة إلكترونية احترافي ثنائية اللغة لمشجعي الكرة المصرية. مبنية بـ Next.js 16 و React 19 مع دمج بوابات دفع محلية. تتميز بنظام سلة هجين، معالجة خلفية بـ BullMQ، وأداء مثالي للموبايل عبر Cloudflare R2.",
    "repoLink": "https://github.com/ahmed-lotfy-dev/zamalek-store",
    "liveLink": "https://zamalek-store.ahmedlotfy.site",
    "coverImage": "/images-downloaded/projects/screencapture-zamalek-store-ahmedlotfy-site-en-2025-12-06-20_06_48-1765597020942.webp",
    "categories": ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "PostgreSQL", "Prisma", "Redis", "BullMQ", "Docker", "Paymob", "Kashier", "Stripe", "Cloudflare R2"],
    "displayOrder": 6,
    "published": true
  },
  {
    "title_en": "POS System",
    "title_ar": "نظام نقاط البيع",
    "slug": "pos-system",
    "desc_en": "A modern, full-stack Point of Sale system built with React, NestJS, and Prisma. Features include real-time inventory management, role-based access control, and a responsive UI designed for speed and reliability.",
    "desc_ar": "نظام نقاط بيع متكامل وعصري مبني باستخدام React و NestJS و Prisma. يتميز بإدارة المخزون في الوقت الفعلي، والتحكم في الوصول القائم على الأدوار، وواجهة مستخدم سريعة وموثوقة.",
    "repoLink": "https://github.com/ahmed-lotfy-dev/pos-system",
    "liveLink": "https://pos-system-app.ahmedlotfy.site",
    "coverImage": "/images-downloaded/projects/Pos-System%20.png",
    "categories": ["React", "NestJS", "Prisma", "PostgreSQL", "Docker", "Tailwind CSS"],
    "displayOrder": 4,
    "published": true
  },
  {
    "title_en": "hi-x.net - LinkTree",
    "title_ar": "hi-x.net - LinkTree",
    "slug": "hi-x",
    "desc_en": "LinkTree-style social contact page for Mohamed Ali (Captain X), a financial markets trader and Golden Ratio analysis expert. Improved and fixed the original site with optimized performance, responsive design, and bilingual (Arabic/English) support with proper RTL/LTR layouts.",
    "desc_ar": "صفحة روابط تواصل اجتماعي بأسلوب LinkTree لمحمد علي (كابتن إكس)، متداول في الأسواق المالية وخبير تحليل النسبة الذهبية. تحسين وإصلاح الموقع الأصلي بأداء محسّن، وتصميم متجاوب، ودعم ثنائي اللغة (عربي/إنجليزي) مع تخطيطات RTL/LTR صحيحة.",
    "repoLink": "https://github.com/ahmed-lotfy-dev/hi-x",
    "liveLink": "https://hi-x.com",
    "coverImage": "/images-downloaded/projects/hi-x-net-2025-10-07-18_23_54.png",
    "categories": ["Frontend", "HTML/CSS", "JavaScript", "Optimization", "Bilingual", "Financial"],
    "displayOrder": 3,
    "published": true
  },
  {
    "title_en": "DevChallenges Portfolio",
    "title_ar": "معرض تحديات المطورين",
    "slug": "dev-challenges",
    "desc_en": "A showcase of my solutions for Responsive Web Design, Javascript, and Front-end Libraries challenges from DevChallenges.io.",
    "desc_ar": "معرض لحلولي لتحديات تصميم الويب المتجاوب، وجافا سكريبت، ومكتبات الواجهة الأمامية من DevChallenges.io.",
    "repoLink": "https://github.com/ahmed-lotfy-dev/dev-challenges-io",
    "liveLink": "https://dev-challenges.ahmedlotfy.surge.sh",
    "coverImage": "/images-downloaded/projects/Generated%20Image%20September%2030,%202025%20-%2012_40PM.png",
    "categories": ["HTML", "CSS", "JavaScript", "Portfolio", "Frontend"],
    "displayOrder": 2,
    "published": true
  },
  {
    "title_en": "AppLicence Manager",
    "title_ar": "مدير تراخيص التطبيقات",
    "slug": "applicence-manager",
    "desc_en": "A secure multi-app license activation platform with an admin dashboard for managing apps, licenses, activations, and status workflows.",
    "desc_ar": "منصة آمنة متعددة التطبيقات لإدارة تفعيل التراخيص مع لوحة تحكم لإدارة التطبيقات والتراخيص وسجل التفعيلات.",
    "repoLink": "https://github.com/ahmed-lotfy-dev/applicence-manager",
    "liveLink": "https://activation.ahmedlotfy.site/",
    "coverImage": "/images-downloaded/projects/applicence-manager/applicence-manager-1771142251845.webp",
    "categories": ["React", "TypeScript", "Bun", "Elysia", "PostgreSQL", "Docker"],
    "displayOrder": 9,
    "published": true
  },
  {
    "title_en": "SelfTracker",
    "title_ar": "SelfTracker",
    "slug": "self-tracker",
    "desc_en": "A minimalist, high-performance mobile app for tracking personal growth metrics (weight, workouts, tasks) built with React Native and Hono.",
    "desc_ar": "تطبيق جوال بسيط وعالي الأداء لتتبع مقاييس النمو الشخصي (الوزن، التمارين، المهام) تم بناؤه باستخدام React Native و Hono.",
    "repoLink": "https://github.com/ahmed-lotfy-dev/selfTracker",
    "liveLink": "https://drive.google.com/file/d/1r1qLiMZwX0oDeq7lQaouEdSs3vUhC8Fg/view?usp=drive_link",
    "coverImage": "/images-downloaded/projects/ezgif.com-animated-gif-maker(1).gif",
    "categories": ["React Native", "Expo", "TypeScript", "Hono", "Bun", "Drizzle ORM", "Mobile"],
    "displayOrder": 5,
    "published": true
  },
  {
    "title_en": "The Drive Center - Modern Automotive Service Platform",
    "title_ar": "ذا درايف سنتر - منصة خدمات السيارات المتكاملة",
    "slug": "the-drive-center",
    "desc_en": "A high-performance, Arabic-first SaaS platform for specialized automotive service centers. Built with Next.js 16 and Drizzle ORM, it features automated booking, customer vehicle tracking, and multi-channel notifications (WhatsApp/Email).",
    "desc_ar": "منصة SaaS متطورة باللغة العربية مخصصة لمراكز خدمة السيارات المتخصصة. تم بناؤها باستخدام Next.js 16 و Drizzle ORM، وتتميز بنظام حجز آلي، وتتبع مركبات العملاء، وإشعارات متعددة القنوات (WhatsApp و Email).",
    "repoLink": "https://github.com/ahmed-lotfy-dev/thedrive.center",
    "liveLink": "https://thedrive.center",
    "coverImage": "/images-downloaded/projects/the-drive-center/the-drive-center-modern-automotive-service-platform-1774137621632.webp",
    "categories": ["Next.js 16", "TypeScript", "PostgreSQL", "Drizzle ORM", "Tailwind CSS", "Better Auth", "Cloudflare R2", "WhatsApp API", "Full-Stack"],
    "displayOrder": 11,
    "published": true
  }
];
