name: Docker Build

on:
  push:
    branches:
      - 'main'
# env:
#   CACHE_IMAGE: mjhea0/docker-ci-cache
#   DOCKER_BUILDKIT: 1
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4

        with:

          context: .
          push: true
          cache-from: type=registry,ref=alotfy2019/my-portofolio:latest
          cache-to: type=inline
          tags: alotfy2019/my-portofolio:latest