name: Docker Build

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn' # or 'npm' | 'pnpm'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        env:
          MONGO_URI: ${{secrets.MONGO_URI}}
          BCRYPT_SALT: ${{secrets.BCRYPT_SALT}}
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}

        with:
          platforms: linux/arm64
          context: .
          push: true
          cache-from: type=registry,ref=alotfy2019/my-portofolio:latest
          cache-to: type=inline
          tags: alotfy2019/my-portofolio:latest