name: Release To Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "19"
          cache: "pnpm"
          uses: docker/build-push-action@v4
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          push: true
          tags: alotfy2019/my-portofolio:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          repository: alotfy2019/my-portofolio
          secrets: |
            "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}"
            "MONGO_URI=${{ secrets.MONGO_URI }}"
            "BCRYPT_SALT=${{ secrets.BCRYPT_SALT }}"
