name: Release To Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          secrets: |
            "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}"
            "MONGO_URI=${{ secrets.MONGO_URI }}"
            "BCRYPT_SALT=${{ secrets.BCRYPT_SALT }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          # pnpm cache files are stored in `~/.pnpm-store` on Linux/macOS
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}
          restore-keys: |
            {{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}
          repository: alotfy2019/my-portofolio

    # #or
    # #registry: ghcr.io
    #       build_extra_args: '{"--build-arg": ["          SENDGRID_API_KEY= ${{ secrets.SENDGRID_API_KEY }},MONGO_URI= ${{ secrets.MONGO_URI }},BCRYPT_SALT= ${{ secrets.BCRYPT_SALT }} ]}'
