name: Release To Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: alotfy2019/my-portofolio:latest
          platforms: linux/amd64,linux/arm64
          cache: "pnpm"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          repository: alotfy2019/my-portofolio
          secrets: |
            "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}"
            "MONGO_URI=${{ secrets.MONGO_URI }}"
            "BCRYPT_SALT=${{ secrets.BCRYPT_SALT }}"

    # #or
    # #registry: ghcr.io
    #       build_extra_args: '{"--build-arg": ["          SENDGRID_API_KEY= ${{ secrets.SENDGRID_API_KEY }},MONGO_URI= ${{ secrets.MONGO_URI }},BCRYPT_SALT= ${{ secrets.BCRYPT_SALT }} ]}'
